var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('','');
subject.inc('',undefined);
subject.inc('','blahundefined');
subject.inc(-1,'');
subject.inc(-1,undefined);
subject.inc(-1,'blahundefined');
subject.inc(1,'');
subject.inc(1,undefined);
subject.inc(1,'blahundefined');
subject.weird('','','','');
subject.weird('','','',"strict");
subject.weird('','','','blah"strict"');
subject.weird('','','','werw');
subject.weird('','','','blahwerw');
subject.weird('','',41,'');
subject.weird('','',41,"strict");
subject.weird('','',41,'blah"strict"');
subject.weird('','',41,'werw');
subject.weird('','',41,'blahwerw');
subject.weird('','',43,'');
subject.weird('','',43,"strict");
subject.weird('','',43,'blah"strict"');
subject.weird('','',43,'werw');
subject.weird('','',43,'blahwerw');
subject.weird('',-1,'','');
subject.weird('',-1,'',"strict");
subject.weird('',-1,'','blah"strict"');
subject.weird('',-1,'','werw');
subject.weird('',-1,'','blahwerw');
subject.weird('',-1,41,'');
subject.weird('',-1,41,"strict");
subject.weird('',-1,41,'blah"strict"');
subject.weird('',-1,41,'werw');
subject.weird('',-1,41,'blahwerw');
subject.weird('',-1,43,'');
subject.weird('',-1,43,"strict");
subject.weird('',-1,43,'blah"strict"');
subject.weird('',-1,43,'werw');
subject.weird('',-1,43,'blahwerw');
subject.weird('',1,'','');
subject.weird('',1,'',"strict");
subject.weird('',1,'','blah"strict"');
subject.weird('',1,'','werw');
subject.weird('',1,'','blahwerw');
subject.weird('',1,41,'');
subject.weird('',1,41,"strict");
subject.weird('',1,41,'blah"strict"');
subject.weird('',1,41,'werw');
subject.weird('',1,41,'blahwerw');
subject.weird('',1,43,'');
subject.weird('',1,43,"strict");
subject.weird('',1,43,'blah"strict"');
subject.weird('',1,43,'werw');
subject.weird('',1,43,'blahwerw');
subject.weird(6,'','','');
subject.weird(6,'','',"strict");
subject.weird(6,'','','blah"strict"');
subject.weird(6,'','','werw');
subject.weird(6,'','','blahwerw');
subject.weird(6,'',41,'');
subject.weird(6,'',41,"strict");
subject.weird(6,'',41,'blah"strict"');
subject.weird(6,'',41,'werw');
subject.weird(6,'',41,'blahwerw');
subject.weird(6,'',43,'');
subject.weird(6,'',43,"strict");
subject.weird(6,'',43,'blah"strict"');
subject.weird(6,'',43,'werw');
subject.weird(6,'',43,'blahwerw');
subject.weird(6,-1,'','');
subject.weird(6,-1,'',"strict");
subject.weird(6,-1,'','blah"strict"');
subject.weird(6,-1,'','werw');
subject.weird(6,-1,'','blahwerw');
subject.weird(6,-1,41,'');
subject.weird(6,-1,41,"strict");
subject.weird(6,-1,41,'blah"strict"');
subject.weird(6,-1,41,'werw');
subject.weird(6,-1,41,'blahwerw');
subject.weird(6,-1,43,'');
subject.weird(6,-1,43,"strict");
subject.weird(6,-1,43,'blah"strict"');
subject.weird(6,-1,43,'werw');
subject.weird(6,-1,43,'blahwerw');
subject.weird(6,1,'','');
subject.weird(6,1,'',"strict");
subject.weird(6,1,'','blah"strict"');
subject.weird(6,1,'','werw');
subject.weird(6,1,'','blahwerw');
subject.weird(6,1,41,'');
subject.weird(6,1,41,"strict");
subject.weird(6,1,41,'blah"strict"');
subject.weird(6,1,41,'werw');
subject.weird(6,1,41,'blahwerw');
subject.weird(6,1,43,'');
subject.weird(6,1,43,"strict");
subject.weird(6,1,43,'blah"strict"');
subject.weird(6,1,43,'werw');
subject.weird(6,1,43,'blahwerw');
subject.weird(8,'','','');
subject.weird(8,'','',"strict");
subject.weird(8,'','','blah"strict"');
subject.weird(8,'','','werw');
subject.weird(8,'','','blahwerw');
subject.weird(8,'',41,'');
subject.weird(8,'',41,"strict");
subject.weird(8,'',41,'blah"strict"');
subject.weird(8,'',41,'werw');
subject.weird(8,'',41,'blahwerw');
subject.weird(8,'',43,'');
subject.weird(8,'',43,"strict");
subject.weird(8,'',43,'blah"strict"');
subject.weird(8,'',43,'werw');
subject.weird(8,'',43,'blahwerw');
subject.weird(8,-1,'','');
subject.weird(8,-1,'',"strict");
subject.weird(8,-1,'','blah"strict"');
subject.weird(8,-1,'','werw');
subject.weird(8,-1,'','blahwerw');
subject.weird(8,-1,41,'');
subject.weird(8,-1,41,"strict");
subject.weird(8,-1,41,'blah"strict"');
subject.weird(8,-1,41,'werw');
subject.weird(8,-1,41,'blahwerw');
subject.weird(8,-1,43,'');
subject.weird(8,-1,43,"strict");
subject.weird(8,-1,43,'blah"strict"');
subject.weird(8,-1,43,'werw');
subject.weird(8,-1,43,'blahwerw');
subject.weird(8,1,'','');
subject.weird(8,1,'',"strict");
subject.weird(8,1,'','blah"strict"');
subject.weird(8,1,'','werw');
subject.weird(8,1,'','blahwerw');
subject.weird(8,1,41,'');
subject.weird(8,1,41,"strict");
subject.weird(8,1,41,'blah"strict"');
subject.weird(8,1,41,'werw');
subject.weird(8,1,41,'blahwerw');
subject.weird(8,1,43,'');
subject.weird(8,1,43,"strict");
subject.weird(8,1,43,'blah"strict"');
subject.weird(8,1,43,'werw');
subject.weird(8,1,43,'blahwerw');
subject.fileTest('','');
subject.fileTest('','');
subject.fileTest('','pathContent/file2');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','pathContent/file2');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','pathContent/file2');
mock.restore();
mock({});
	subject.fileTest('','pathContent/file2');
mock.restore();
subject.fileTest('','pathContent/file2');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','pathContent/file2');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','pathContent/file2');
mock.restore();
mock({});
	subject.fileTest('','pathContent/file2');
mock.restore();
subject.fileTest('','pathContent/file1');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('','pathContent/file1');
mock.restore();
subject.fileTest('','pathContent/file1');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('','pathContent/file1');
mock.restore();
subject.fileTest('','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('','path/filenotExist');
mock.restore();
subject.fileTest('','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('','path/filenotExist');
mock.restore();
subject.fileTest('','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('','path/filenotExist');
mock.restore();
subject.fileTest('','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('','path/filenotExist');
mock.restore();
subject.fileTest('path/fileExists','');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','');
mock.restore();
subject.fileTest('path/fileExists','');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file2');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file2');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file1');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file1');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.fileTest('path/fileExists','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
subject.fileTest('path/fileExists','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
subject.fileTest('path/fileExists','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
subject.fileTest('path/fileExists','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
subject.fileTest('path/fileExists','');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','');
mock.restore();
subject.fileTest('path/fileExists','');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file2');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file2');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file1');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file1');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.fileTest('path/fileExists','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
subject.fileTest('path/fileExists','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
subject.fileTest('path/fileExists','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
subject.fileTest('path/fileExists','path/filenotExist');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/filenotExist');
mock.restore();
subject.normalize('');
subject.format('','','');
subject.format('','','hello');
subject.blackListNumber('');
subject.blackListNumber('312-123-4567');
subject.blackListNumber('x00-123-4567');
